# base image
FROM mhart/alpine-node:12.22.3 as build

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install

# add app
COPY . /app

# add resume, get dependency first
RUN apk update \                                                                                                                                                                                                                        
    &&  apk add ca-certificates wget \                                                                                                                                                                                                      
    &&  update-ca-certificates  \
    &&  wget -O resume.pdf https://raw.githubusercontent.com/shahdeys/resume/master/resume.pdf

# expose 4200 and DEBUG 9229
EXPOSE 9229
EXPOSE 4200

CMD ng serve --host 0.0.0.0 --port 4200