name: Test
on:
  push:
    branches-ignore:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [ '1.16.1' ]
        otp: [ '26.2.2' ]
    steps:
      - name: Checkout Github repo
        uses: actions/checkout@v3
      - name: Sets up an Erlang/OTP environment
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Retrieve cached dependencies
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}
      - run: mix deps.get && mix test --cover

