name: Release & Deploy to Production
on: 
  push:
    branches:
    - master
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Release & Deploy to Production
      # uses latest Ubuntu LTS, barf - it was either this or Windows Server LUL
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only